# This configuration file will make Travis CI compile our PDF and force-push
# it back to the repository.

# By Dan Foreman-Mackey with modifications from Andy Casey

# Travis needs to be provided with the environment variables:
# - GITHUB_USER:    your GitHub username
# - GITHUB_API_KEY: a personal access token - make sure that it has access to
#                   'repo' - https://github.com/settings/tokens

sudo: false
language: python
install:
    - source .ci/setup-texlive.sh
before_script: # configure a headless display to test plot generation
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start
script:
    - source .ci/travis.sh
notifications:
    email:
       on_success: change
       on_failure: always
